Ws pixel
nekromant322/TwitchMentorBot pull request #21
Opened 2023-04-28 17:58 UTC by etozhealexis

ну я чета поделал, но не имею возможности проверить работает или нет))

2023-04-28 18:13 UTC, nekromant322 commented on src/main/resources/static/js/pixelPanel.js
> +});
а нафига перерисовывать все сразу по ивенту из ws?  
вроде договаривались же по сокету гнать координаты и цвет пикселя, который надо поменять

2023-04-28 18:14 UTC, nekromant322 commented on src/main/java/com/nekromant/twitch/config/WebSocketConfig.java
> +        registry.addEndpoint("/ws").withSockJS();
а зачем оба-два?

2023-04-28 18:15 UTC, nekromant322 commented on src/main/java/com/nekromant/twitch/contoller/WebSocketController.java
> +        return new PixelState();
почему возвращается пусто PixelState?

2023-04-28 18:15 UTC, nekromant322 requested changes
Задействовать вебсокеты для отрисовки

2023-04-29 22:20 UTC, nekromant322 commented on pom.xml
> +		</dependency>
ctrl alt l?

2023-04-29 22:22 UTC, nekromant322 commented on src/main/java/com/nekromant/twitch/contoller/WebSocketController.java
> +        }
что?

2023-04-29 22:24 UTC, nekromant322 commented on src/main/java/com/nekromant/twitch/contoller/WebSocketController.java
> +        return pixel;
возвращается тот же что прислали?

2023-04-29 22:26 UTC, etozhealexis commented on src/main/java/com/nekromant/twitch/contoller/WebSocketController.java
> +        }
опечатка, там redeempixel

2023-05-02 08:30 UTC, nekromant322 requested changes
Нужно подлечить по минимуму грязный код

2023-05-02 08:30 UTC, nekromant322 commented on src/main/java/com/nekromant/twitch/service/RedeemedPixelsService.java
> +            return tokenUser.getUser(token);
А зачем два похода в кеш? Может же одним через переменную

2023-05-02 08:30 UTC, nekromant322 commented on src/main/java/com/nekromant/twitch/service/RedeemedPixelsService.java
> +        return null;
Что за любовь к null, можно же эксепшоны бросать..

2023-05-02 09:01 UTC, etozhealexis commented on src/main/java/com/nekromant/twitch/service/RedeemedPixelsService.java
> +        return null;
Рефакторил Машин код, да недорефакторил

2023-05-03 11:16 UTC, nekromant322 approved these changes

2023-05-03 11:31 UTC, merged