Feature/create kindness command
nekromant322/TwitchMentorBot pull request #38
Opened 2023-06-09 17:11 UTC by EduardCoool

2023-06-10 15:22 UTC, nekromant322 commented on src/main/java/com/nekromant/twitch/model/TwitchUser.java
> +    private String name;
-> login

2023-06-10 15:22 UTC, nekromant322 commented on src/main/java/com/nekromant/twitch/service/TwitchUserService.java
> +        String nameTwitchUser = event.getMessageEvent().getUser().getName();
возможно лучше по login сохранять, потому что username можно поменять в любой момент  
посмотри что маша для пикселей использовала

2023-06-10 15:23 UTC, nekromant322 requested changes
сохранять мессаджи по логину

2023-06-12 18:31 UTC, etozhealexis commented on src/main/java/com/nekromant/twitch/model/TwitchUserMessage.java
> +@Data
Нк используй эту анноташку для @Entity, могут возникнуть проблемы с переопределенными equals() и hashcode()

2023-06-13 09:32 UTC, merged